# Setup
title:               Lunbrilo
tagline:             ''
description:         ''
url:                 https://peonies22.github.io
baseurl:             ''
paginate:            2
permalink:           pretty


# Gems
plugins:
  - jekyll-paginate
