# Setup
title:               Lunbrilo
tagline:             'A blog'
description:         ''
url:                 https://peonies22.github.io
baseurl:             ''
#paginate:            5
permalink:           pretty


# Gems
plugins:
  - jekyll-paginate
